README.md

The original link was devoid of branching information, so it takes you to a 404.
A hardcoded link works better because it doesn't mess up on the branch information
in the url.

Fix link to company listing page

---

app/models/company.rb

Adding NCS that uses Ruby and Hiring for Ruby on Rails Developers
NCS is currently hiring Ruby on Rails Developers and we are also looking for DevOps people.

Adding NCS that uses Ruby and Hiring for Ruby on Rails Developers

---

app/models/company.rb

We haven't gotten ourselves a shiny careers page yet, but we're hiring; 
the mailto link will help get in touch with us quickly on careers at Mesitis.

Add hiring mailto link on Canopy's listing

---

config/initializers/companies.yml

Grab recently acquired grab.com, and thus the domains have to be updated.

Update Grab domain

---

app/assets/stylesheets/companies.scss
app/views/application/companies.html.slim
config/initializers/companies.yml

Changed to CSS background approach of rendering the image. This brings the benefit of not showing the broken img icon if the img link is broken.
This partially fixes #131. I did not use a placeholder image, instead the image will be empty as mentioned above. I think it's more elegant than using JS to listen for error events and I'm not really keen to add N event listeners for N images.
Lastly I uploaded Aureso's logo to some free img hosting site and fixed the broken img path problem.

Refactor companies image markup

---

app/views/application/index.html.slim

Since you can no longer register for RDRC, changed to a link to the talks over at Engineers. 🙂

Change RDRC registration link to a link to the talks

---

config/initializers/companies.yml

https://e27.co/singapore-cleaning-services-provider-properhands-shut-thursday-20170612/

Remove Company ProperHands, which no longer exists

---

app/views/companies/index.html.slim
spec/controllers/companies_controller_spec.rb

Font Awesome updated their view helper signature. This caused the companies page to break. This change does:
- Do `render_views` in the companies controller spec, to cover the error.
- Update the FA call on the companies page.

Fix font awesome breakage

---

config/initializers/companies.yml

Add Stripe to the companies listing. Included contribution count = 1 for hosting the June 2018 meet-up.

Add Stripe to companies

---

app/assets/stylesheets/base.scss
app/views/application/index.html.slim

Social icons on the front page are not displaying correctly. Screenshot:
We have upgraded Font Awesome, and in version 5 and above, the icons are namespaced. Instead of `fa`, we need to use `fab` for brand icons.
Changed to use the `#icon` helper, and added the right prefix. Screenshot:

Fix the social icons on the front page not displaying

---

app/views/application/index.html.slim

This is a temporary measure to prevent bots from signing up and signing in to our Slack workspace. A proper solution would be to add a CAPTCHA here.

Hide Slack self-invite form

---

app/views/application/index.html.slim

- Fix broken telegram group link on landing page
- Address issue: https://github.com/rubysg/rubysg-reboot/issues/318

Fix broken telegram group link

---

app/models/company.rb
app/views/companies/index.html.slim
db/data/companies.yml
spec/models/company_spec.rb

I find that the list of companies a little outdated. So I want to
1. feature recent companies more
2. keep contributed companies as a token of appreciation. let the name live on forever! 
3. include a nodeflair link that filters all the Ruby jobs out there so that people know where to find Ruby jobs. 
https://www.nodeflair.com/jobs?query=&page=1&tech_stacks%5B%5D=Ruby

make /companies more relevant 

---

app/controllers/forms_controller.rb
app/forms/feedback/behind_the_gems2.rb
app/forms/feedback_form.rb
app/models/form_response.rb
app/views/forms/show.html.slim
config/routes.rb
db/migrate/20210912145012_create_form_responses.rb
db/schema.rb
spec/controllers/forms_controller_spec.rb
spec/forms/feedback/behind_the_gems2_spec.rb
spec/forms/feedback_form_spec.rb
spec/models/form_response_spec.rb

I want to create forms on RubySG so that I can collect feedbacks from meetup participants. 
The requirements are: 
1. No admin page to CRUD forms. Ruby.sg currently does not have admin pages and I do not want to set a precedence for it.
2. I want to be able to have multiple forms and collect feedbacks for each. This is so that I can create one feedback form for each event (eg. meetup) 
1. I want to be able to create forms with code. 
```ruby 
class ThisIsAForm
title "Meetup - Jan 2021"
questions [{
question: "How would you rate today's meetup?"
...
}, {
question: "Any suggestions to make this better?"
...
}]
end
```
2. A url should be immediately available for the form so that I can answer the question
```
https://ruby.sg/forms/this_is_a_form
```
The implementation consists of 4 parts: …

A basic form creation and submission framework

---

app/assets/stylesheets/base.scss
app/views/application/index.html.slim

Currently, when the screen is small the icons go out of screen.
Solution is to use css grid instead and make each row to only have 2 item.

use css grid to position company logos

---

app/assets/stylesheets/base.scss

There is a footer at the border which is not supposed to be there. This PR Removed the border.

remove footer border

---

app/helpers/application_helper.rb
app/views/application/index.html.slim

Add a link to help discoverability of our recordings. We should invest in keeping content updated in https://engineers.sg. 
| before | after |
| --- | --- |
|<img width="422" alt="Screenshot 2022-10-02 at 12 42 29 PM" src="https://user-images.githubusercontent.com/10722197/193438228-265390ba-e609-4317-83cb-676501196e81.png">  | <img width="422" alt="Screenshot 2022-10-02 at 12 42 33 PM" src="https://user-images.githubusercontent.com/10722197/193438231-2e0e183e-70c4-4238-9ed6-7d869fd7dfc8.png"> |

add link to watch recordings in engineers.sg

---

app/views/layouts/application.html.slim

I want to start tracking some stats for the https://ruby.sg and ended up with the Google Analytics. 
Other options I have explored
1. Google Analytics Alternatives. 
1. I've checked out other Google Analytics Alternatives and it all requires a paid plan for reasonable basic usage. 
2. Use [active_analytics](https://github.com/BaseSecrete/active_analytics) which saves the visit request stats directly into the database. 
1. But we have a database limit of 1GB for fly.io's free tier. If we go down this route, it might be hard to switch out in the future. 
2. Only can track pages that ruby.sg owns. If its a link to another website (eg. meetup.com events page or rubysg engineers.sg page), then no stats will be recorded

Add Google Analytics

---

app/views/layouts/application.html.slim

Reverts rubysg/rubysg-reboot#370 because it does not track external link clicks which is mostly what I need.

Revert "Add Google Analytics"

---

Gemfile
Gemfile.lock
config/environments/production.rb

Remove Uglifier and stop configuring js_preprocessor. This is because Uglifier is causing build problems (See stacktrace below). Not too sure why do we need a js_preprocessor tbh but I checked newer RoR codebases and they do not configure js_preprocessors
Stacktrace when doing `bin/rails fly:build` before deploy. [GitHub action failed job](https://github.com/rubysg/rubysg-reboot/actions/runs/3404672067/jobs/5662175145)
```
#24 [stage-4 6/6] RUN bin/rails fly:build
#24 5.401 /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.1/lib/active_job/serializers.rb:30:in `serialize': Unsupported argument type: Object (ActiveJob::SerializationError)
#24 5.402 	from /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.1/lib/active_job/arguments.rb:122:in `serialize_argument'
#24 5.402 	from …
```

remove uglifier

---

app/helpers/application_helper.rb
app/views/application/index.html.slim

Collect photo into an icloud album because it's easy for me to new photos for folks with iPhone. So far, 2/3 of the organisers use iPhone so its a balance. We can migrate to another photo hosting service if a better one comes up.

add link to photo album

---

app/views/application/index.html.slim

This PR fixes the spacing issue for buttons for mobile screen size. Fix the issue by adding margin right and margin bottom. 
| Before | After | 
| --- | --- |
| <img width="397" alt="Screenshot 2022-11-10 at 12 04 36 AM" src="https://user-images.githubusercontent.com/10722197/200880356-a90b929f-16d6-421c-acd5-447ba69dbc27.png"> | <img width="397" alt="Screenshot 2022-11-10 at 12 05 35 AM" src="https://user-images.githubusercontent.com/10722197/200880450-f04eea3d-1416-4794-905f-b7a521bc0d50.png"> |

fix button spacing for responsive view

---

.github/workflows/ci.yml
.github/workflows/deploy_to_fly.yml

This is causing deploy to fail because node12 is deprecated.

upgrade actions/checkout to v3

---

.github/workflows/ci.yml
.github/workflows/deploy_to_fly.yml

We are running `ci.yml` and `deploy_to_fly.yml` after every merge. Instead of doing this which doesn't block deploy when CI fails, 
1. stop running `ci.yml` after merge
2. start running tests into `deploy_to_fly.yml`

Update GH action pipelines

---

.github/workflows/deploy_to_fly.yml

Test and deploy are running async. This PR makes them run 1 after another.

Make test and deploy steps synchronous

---

app/jobs/ping_job.rb
config/initializers/scheduler.rb

RubySgBot hasn't been very consistent in pushing the RubyWeekly articles to the RubySG telegram group every friday..
I'm wondering if fly.io is putting the application to sleep because of the extremely low traffic for https://ruby.sg which results in the scheduler not running because it is hosted on the web instance. So I'm scheduling a ping job at 12am and 12pm to see if I can keep the app alive until tomorrow and see if the RubyWeekly articles get sent.

add PingJob to see if keeping the app alive ensures RubyWeekly messages get sent
