rubysg/rubysg-reboot

app/views/layouts/application.html.slim
spec/controllers/application_controller_spec.rb
spec/rails_helper.rb

- Include Active Support Time helper in RSpec config block.
- Test ApplicationController#index
- Test view when year changes
So that when we time travel to 2046, @winston's birthday party can still see this site display in correct year. :wink:

Test ApplicationController and automate year display.

---

README.md

Switch to svg badges. [ci skip]

---

.travis.yml
bin/setup

- Enable docker based container
- Enable bundler cache
- test ruby-head
- fast_finish when ruby 2.2.1 finished.
This pull request is to fix the build.

Run bin/setup on travis.

---

app/models/company.rb

Add in Tinkerbox to companies page

---

README.md
app/models/company.rb

Add Ruckus Wireless company info

---

app/models/company.rb

@winston This is awesome! Thanks for setting up this page :kissing_heart:

Add ReferralCandy to company list

---

app/models/company.rb

Add Neo to companies list (including logo)

add neo info to company.rb

---

app/models/company.rb

add cantab ip to list of companies in singapore using ruby

---

app/models/company.rb

Added ESTL in list of Singapore companies using Ruby

---

app/models/company.rb

Thank you very much for doing this! :smile:

Add TradeGecko to company listing

---

app/models/company.rb

Fix Ruckus logo type and resolution

---

app/models/company.rb

Extending existing constant LIST by additional hash, 
containing meta-data about Aureso company.

Adding Aureso into the list of Companies

---

app/models/company.rb

Add Ricoh to list of companies

---

app/models/company.rb

Append honestbee information to the constant `Company::LIST`

Add honestbee to list of companies

---

app/assets/stylesheets/companies.scss
app/views/application/companies.html.slim

Customize hover effect for company listing
- Increase font-size for name
- Move the address-contact down
- Add a border around the company
With :heart:

Add hover effect for companies listing, refer to #58

---

app/models/company.rb

A bit late to the party, but finally added! :smile:

added Kaligo to list of companies

---

app/models/company.rb

We would like to omit the email field, is this okay?

added SMART to the LIST

---

app/models/company.rb

Add SourceClear to companies using ruby

---

app/models/company.rb

Update Grab company details

---

config/initializers/companies.yml

A naive fix, removing nil from hiring_urls. Looks fine on rails s, but really need to write tests (TODO). Leave for another PR.

Fix Companies Not Hiring Showing as Hiring

---

app/assets/stylesheets/companies.scss
app/views/application/companies.html.slim
config/initializers/companies.yml

Make companies page 2 columns

---

config/initializers/companies.yml

Adding Pocketmath to the list of companies using Ruby in Singapore.

Add Pocketmath to companies

---

config/initializers/companies.yml

Our website now has a career page! 🎉

Update Tinkerbox hiring URL to new career page

---

config/initializers/companies.yml

Update GDS@Hive URL and Email Address

---

config/initializers/companies.yml

Add EngageRocket to list of companies

---

config/initializers/companies.yml

As the company is no longer active :(

Removing Roomorama from the list of companies

---

config/initializers/companies.yml

Add MoneySmart to the list of companies

---

config/initializers/companies.yml

Updating the information for ReferralCandy. Let me know if there's anything else to be done. :)

Update company information for ReferralCandy

---

config/initializers/companies.yml

Remove unresponsive outdated companies info

---

config/initializers/companies.yml

Do let me know if there is anything else to be done. Thanks!

Update company information for Viki

---

config/initializers/companies.yml

- Update honestbee company profile and logo

Update honestbee company profile and image

---

config/initializers/companies.yml

Also update contribution counts of Wantedly and EngageRocket, for Dec & Nov meetups
See [staging app ](https://rubysg-staging.herokuapp.com/companies) for visuals

Add Wantedly and additional companies on its platform

---

config/initializers/companies.yml

Adding the Sephora company information

Add Sephora company information

---

config/initializers/companies.yml

Add agilelab to company info

---

config/initializers/companies.yml

Updated hiring link for Agile Lab

Update agilelab company info

---

Gemfile
Gemfile.lock

Addresses #274.
@Drenmi could you take a look if this could be merged?

Remove 12factor

---

.travis.yml
Gemfile.lock
config/initializers/companies.yml

- Remove shopventure (closed)
- Remove jollygoodcode (dormant)
- Add email to Shopify hiring
@hanmd82 @Drenmi I believe there are also other companies which are no longer active. I don't want to be presumptuous and delete them. Any suggestions on how we can clean this up?
- email them and if email bounce or no reply then delete?
- ping them here on an issue? 
wdyt?

Updates on companies.yml

---

config/initializers/companies.yml

Kaligo Solutions is now Ascenda Loyalty

---

.github/workflows/ci.yml

Travis is like not working already so I'm replacing it with GitHub actions

use GitHub actions to run CI

---

app/forms/feedback/behind_the_gems4.rb
spec/forms/feedback/behind_the_gems4_spec.rb

New form for november meetup. The feedbacks coming in are really helpful so we definitely should continue collecting them.

add new form for november meetup

---

app/forms/feedback/behind_the_gems5.rb
spec/forms/feedback/behind_the_gems5_spec.rb

Need this to collect feedback for meetup.

add form for behind the gems 5

---

db/data/companies.yml

Updated the url to the active one

Update job page for Sephora Singapore

---

app/helpers/application_helper.rb

Forgot to update the QR code in https://github.com/rubysg/rubysg-reboot/pull/351!

Update Telegram group QR code generator link

---

app/assets/stylesheets/base.scss
app/helpers/application_helper.rb
app/views/application/index.html.slim

1. Fix broken Telegram Link
2. Update meetup days to 1st Wednesday of the month
3. Fix unequal spacing on website.

fix broken tg link and standardize spacing

---

db/data/companies.yml

* got the logo from Sam and update in the codebase.

fix broken silicon jungle link

---

app/forms/feedback/meetup03082022.rb
spec/forms/feedback/meetup03082022_spec.rb

Create a feedback form so that we can gather feedback.

add feedback form for august 2022 meetup

---

.dockerignore
.github/workflows/deploy_to_fly.yml
Dockerfile
fly.toml
lib/tasks/fly.rake

Followed the guide [here](https://fly.io/docs/rails/getting-started/migrate-from-heroku/) and I've tested that everything is working already 👍 https://ruby.sg is already pointing to the fly app. The Dockerfile can use some improvement though.

Move ruby.sg to fly

---

app/assets/stylesheets/companies.scss

Reduce the spacing for company address. 
| Before | After | 
| --- | --- | 
| <img width="1345" alt="Screenshot 2022-11-06 at 11 19 30 PM" src="https://user-images.githubusercontent.com/10722197/200179241-035d99e2-46ce-4b1e-9ff6-c0a9a7f25071.png"> | <img width="1345" alt="Screenshot 2022-11-06 at 11 19 40 PM" src="https://user-images.githubusercontent.com/10722197/200179249-1118c6de-329b-4c2f-ad52-5943cadeba40.png"> |
The spacing and the various edge cases.

reduce the height for company address

---

README.md
db/data/companies.yml

Changes: 
- Adds Coingecko to db/data/
- Fixes broken link in README to `companies.yml`

Add CoinGecko listing

---

db/data/companies.yml

Add GitLab to list of companies, since we have an entity in Singapore.
@TayKangSheng @zonghangoh take a look please 😄

Add GitLab to companies.yml

---

.github/workflows/deploy_to_fly.yml
Gemfile
Gemfile.lock
Makefile
Procfile
bin/delayed_job
config/environments/development.rb
config/environments/production.rb
config/initializers/scheduler.rb
db/migrate/20230721152407_create_delayed_jobs.rb
db/schema.rb
fly.worker.toml

Trying to get more stability with the weekly sending of the RubyWeekly articles. After testing the code, it doesn't seem like there is anything wrong so I suspect there is something weird going on with fly.io. I added 1 job worker and move jobs from inline to a queue to see if it stablise things.

Add Delayed Job and 1 job worker in fly.io

---

Makefile

Fix Makefile syntax error

---

Makefile
fly.db.toml

Upgraded the machine that is hosting the database to v2 apps on fly. Since it gave me a config file for the machine, might as well just save it. 
https://community.fly.io/t/fly-migrate-to-v2-postgres-edition/12140

Add fly config for database machine on Fly 
